import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Fascinate_Inline, Zain } from 'next/font/google';
import Footer from "./footer";

const fascinateInline = Fascinate_Inline({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-fascinate-inline',
});

const zain = Zain({
  subsets: ['latin'],
  weight: ['400', '700', '800', '900'],
  variable: '--font-zain',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${zain.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
